### ISSUE TITLE
NameError: uninitialized constant StoreModel::Types::ArrayType

### ISSUE THREAD

**Issue by alkesh26** [DmitryTsepelev/store_model#130]
We recently upgraded our application from Rails 5.2.8 to the 6.1.7 version. We are using the 3.1.2 Ruby version and the 1.2.0 version of the StoreModel gem.

We sometimes face the below error on our production servers (triggered randomly).

```
uninitialized constant StoreModel::Types::ArrayType

            candidate = constant.const_get(name)
                                ^^^^^^^^^^
```

A stack trace of the above error is as below:

```
ArgumentError: undefined class/module StoreModel::Types::ArrayType
  from <internal:marshal>:34:in `load'
  from activesupport (6.1.7) lib/active_support/core_ext/marshal.rb:8:in `load'
  from activerecord-session_store (2.0.0) lib/active_record/session_store.rb:54:in `load'
  from activerecord-session_store (2.0.0) lib/active_record/session_store.rb:19:in `deserialize'
  from activerecord-session_store (2.0.0) lib/active_record/session_store/session.rb:64:in `data'
  from activerecord-session_store (2.0.0) lib/action_dispatch/session/active_record_store.rb:148:in `find_session'
  from rack (2.2.4) lib/rack/session/abstract/id.rb:314:in `load_session'
  from actionpack (6.1.7) lib/action_dispatch/middleware/session/abstract_store.rb:45:in `block in load_session'
  from actionpack (6.1.7) lib/action_dispatch/middleware/session/abstract_store.rb:53:in `stale_session_check!'
  from actionpack (6.1.7) lib/action_dispatch/middleware/session/abstract_store.rb:45:in `load_session'
  from actionpack (6.1.7) lib/action_dispatch/request/session.rb:234:in `load!'
  from actionpack (6.1.7) lib/action_dispatch/request/session.rb:226:in `load_for_read!'
  from actionpack (6.1.7) lib/action_dispatch/request/session.rb:92:in `[]'
  from turbolinks (5.2.1) lib/turbolinks/redirection.rb:44:in `set_turbolinks_location_header_from_session'
  from activesupport (6.1.7) lib/active_support/callbacks.rb:427:in `block in make_lambda'
``` 

`StoreModel::Types::ArrayType` was a class present under `lib/store_model/types/` directory till 0.7.0 version. The error should not appear in the latest version. Let me know if I missed any steps when we upgraded our Rails app.

**Comment by alkesh26** [comment]
@DmitryTsepelev, any updates on the above concern?
